default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

<% data_dir = ENV.fetch("RUNABOUT_DATA_DIR", Rails.root.join('tmp', 'second_screen')) %>
<% %w[development production].each do |environment| %>
<%= environment %>:
  primary:
    <<: *default
    database: <%= File.join(data_dir, "#{environment}.sqlite3") %>
  queue:
    <<: *default
    database: <%= File.join(data_dir, "#{environment}_queue.sqlite3") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= File.join(data_dir, "#{environment}_cable.sqlite3") %>
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: <%= File.join(data_dir, "#{environment}_cache.sqlite3") %>
    migrations_paths: db/cache_migrate
<% end %>

test:
  <<: *default
  database: storage/test.sqlite3
